# Lesson 1 — What is pandas?
**Goal:** understand the two core objects — the `Series` (one column) and the `DataFrame` (a table) — using a tiny sales table from our shop, **Duka Bora**.

> Real-world angle: every spreadsheet you've used is a DataFrame. pandas lets you do with code what you do by hand in Excel — but repeatable, and on millions of rows.

In [1]:
import pandas as pd
import numpy as np
pd.__version__

'3.0.2'

## A Series = one labelled column
Think: the *Price* column of a price list. Values plus an **index** (the labels).

In [2]:
prices = pd.Series([25000, 45000, 85000, 18000],
                   index=['Wireless Mouse', 'USB-C Charger', 'Bluetooth Earbuds', 'Flash Drive'],
                   name='price_tzs')
prices

Wireless Mouse       25000
USB-C Charger        45000
Bluetooth Earbuds    85000
Flash Drive          18000
Name: price_tzs, dtype: int64

In [3]:
# Look up by label, do maths on the whole column at once (no loops!)
print(prices['Bluetooth Earbuds'])
print(prices.mean())
prices * 1.18   # add 18% VAT to every price

85000
43250.0

Wireless Mouse        29500.0
USB-C Charger         53100.0
Bluetooth Earbuds    100300.0
Flash Drive           21240.0
Name: price_tzs, dtype: float64

## A DataFrame = a table of Series that share an index
Each column is a Series. Here are 5 orders from today:

In [4]:
orders = pd.DataFrame({
    'order_id': ['O001', 'O002', 'O003', 'O004', 'O005'],
    'product':  ['Wireless Mouse', 'Smartphone 128GB', 'Flash Drive', 'Bluetooth Earbuds', 'Wireless Mouse'],
    'quantity': [2, 1, 4, 1, 1],
    'unit_price': [25000, 650000, 18000, 85000, 25000],
    'branch':   ['Kariakoo', 'Mlimani City', 'Kariakoo', 'Arusha CBD', 'Mwanza Rock City'],
})
orders

  order_id            product  quantity  unit_price            branch
0     O001     Wireless Mouse         2       25000          Kariakoo
1     O002   Smartphone 128GB         1      650000      Mlimani City
2     O003        Flash Drive         4       18000          Kariakoo
3     O004  Bluetooth Earbuds         1       85000        Arusha CBD
4     O005     Wireless Mouse         1       25000  Mwanza Rock City

In [5]:
orders.shape   # (rows, columns)

(5, 5)

In [6]:
orders.dtypes  # the type of each column

order_id        str
product         str
quantity      int64
unit_price    int64
branch          str
dtype: object

## Your first calculation: revenue per order
Multiply two columns → a new column. pandas lines them up row by row.

In [7]:
orders['revenue'] = orders['quantity'] * orders['unit_price']
orders

  order_id            product  quantity  unit_price            branch  revenue
0     O001     Wireless Mouse         2       25000          Kariakoo    50000
1     O002   Smartphone 128GB         1      650000      Mlimani City   650000
2     O003        Flash Drive         4       18000          Kariakoo    72000
3     O004  Bluetooth Earbuds         1       85000        Arusha CBD    85000
4     O005     Wireless Mouse         1       25000  Mwanza Rock City    25000

In [8]:
print('Total revenue today: TSh', f"{orders['revenue'].sum():,}")
print('Best-selling order:', orders.loc[orders['revenue'].idxmax(), 'product'])

Total revenue today: TSh 882,000
Best-selling order: Smartphone 128GB

## Key takeaways
- `Series` = 1-D labelled array; `DataFrame` = 2-D table of Series.
- Operations apply to **whole columns** (vectorised) — no `for` loops.
- `shape`, `dtypes` tell you what you're working with.

**Exercise:** add a column `revenue_usd` using 1 USD = 2,600 TSh, rounded to 2 decimals.